FROM nvcr.io/nvidia/nemo:25.07.02@sha256:abd486b84f7140bc0c90b138bf5962af1d3c50e31cd7906c523bb9e79081cbb7
SHELL ["/bin/bash", "-lc"]
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo
# install git-lfs
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get update ; apt-get install git-lfs
RUN git lfs install
WORKDIR /workspace
RUN source /opt/venv/bin/activate && \
    git clone https://github.com/NVIDIA-NeMo/Run.git && \
    cd Run && \
    git checkout f5970c59529949593b845476348da16c8235289b && \
    pip install . --no-cache-dir
RUN apt clean all && \
    rm -rf /var/lib/apt/lists/*
